required = [
  "github.com/golang/mock/mockgen"
]

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/google/uuid"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.2.2"

[[constraint]]
  name = "github.com/golang/mock"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.6"

[[constraint]]
  name = "github.com/DATA-DOG/go-sqlmock"
  version = "^1.3.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "^1.0.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "^1.9.1"

[prune]
  go-tests = true
  unused-packages = true
